version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

  pre_build:
    commands:
      - npm pkg delete scripts.prepare
      - yarn install --lock-file

  build:
    commands:
      - yarn build

  post_build:
    commands:
      - aws s3 sync --delete ./dist s3://pedrobarrosportfolio-bucket
      - aws cloudfront create-invalidation --distribution-id EXMA36D4K6PP5 --paths /index.html
